server:
  port: 8989
  servlet:
    context-path: /ems

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems?characterEncoding=UTF-8
    username: root
    password: 123456
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/





mybatis:
  mapper-locations: classpath:/com/yswu/mapper/*.xml
  type-aliases-package: com.yswu.ems.entity
